### ISSUE TITLE
Axis out of bounds

### ISSUE THREAD

**Issue by Harsh151200** [ZhihuaLiuEd/canetbrats#2]
AxisError: Caught AxisError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/BE Project/Codes/Main/Segmentation/CA-NET/canetbrats-master/bratsDataset.py", line 71, in __getitem__
    self.maxIntensityShift
  File "/content/drive/MyDrive/BE Project/Codes/Main/Segmentation/CA-NET/canetbrats-master/dataProcessing/augmentation.py", line 79, in augment3DImage
    lbl[:, :, z, :] = utils.dense_image_warp(lbl[:, :, z, :], dx_img, dy_img, interpolationMethod)
  File "/content/drive/MyDrive/BE Project/Codes/Main/Segmentation/CA-NET/canetbrats-master/dataProcessing/utils.py", line 65, in dense_image_warp
    print(f"IM remapped : {remapped.ndim } and IM : {im.ndim}")
  File "<__array_function__ internals>", line 6, in expand_dims
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/shape_base.py", line 597, in expand_dims
    axis = normalize_axis_tuple(axis, out_ndim)
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 1358, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py", line 1358, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 3 is out of bounds for array of dimension 3

**_Getting this axis out of Bound issue. Please help me out with this !!_**

**Comment by ZhihuaLiuEd** [comment]
Try to set NN_AUGMENTATION = False (You can find related code generating this error on bratsDataset.py).

Even the code with NN_AUGMENTATION = True works fine on my side. I will run the code and debug this again in a few days.

**Comment by Harsh151200** [comment]
Okay will check this thing

**Comment by yiym** [comment]
Thank you very much for your work, but I have some problems：
numpy.AxisError: axis 3 is out of bounds for array of dimension 3. The question is the same as the above question. 
  You said above that try to set NN_AUGMENTATION = False,but i cannot find this in bratsDataset.py,do I need to add one line of code or how to do it?
  Thank you again.

**Comment by ZhihuaLiuEd** [comment]
Hi,
Its on the /experiments/canet.py, line 59.

What I mean is the error shows in bratsDataset.py is traced to self.nnAugmentation = expConfig.NN_AUGMENTATION, which is finally located at the hard coded parameter in the model.

**Comment by yiym** [comment]
Thank you for taking the time to answer my questions patiently. I will check the errors according to your opinions. I wish you a happy life and smooth work.





------------------ Original ------------------
From: Zhihua Liu ***@***.***&gt;
Date: Mon,Nov 29,2021 6:45 AM
To: ZhihuaLiuEd/canetbrats ***@***.***&gt;
Cc: yiym ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [ZhihuaLiuEd/canetbrats] Axis out of bounds (#2)





 
Hi,
 Its on the /experiments/canet.py, line 59.
 
What I mean is the error shows in bratsDataset.py is traced to self.nnAugmentation = expConfig.NN_AUGMENTATION, which is finally located at the hard coded parameter in the model.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
